package org.icgc.dcc.pcawg.client.vcf.errors;

public enum PcawgVariantErrors{
  INDEL_MATCHING_REF_ALT_LENGTH_ERROR,
  SNV_MNV_REF_LENGTH_LT_1_ERROR,
  DATA_TYPE_NOT_SUPPORTED,
  SNV_MNV_REF_ALT_LENGTH_NOT_EQUAL_ERROR,
  INDEL_INSERTION_REF_LENGTH_NOT_1_ERROR,
  INDEL_DELETION_ALTH_LENGTH_NOT_1_ERROR,
  REF_ALT_SUBSTRINGS_OF_EACHOTHER_ERROR,
  MUTATION_TYPE_NOT_SUPPORTED_ERROR;
}
